# Generated by Django 3.0.5 on 2020-04-12 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendpg', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Track',
            new_name='Tracks',
        ),
    ]
