# Generated by Django 3.0.5 on 2020-04-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendpg', '0002_auto_20200412_0314'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracks',
            name='artist',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
